# -*- coding: utf-8 -*-
import json
import os
# Form implementation generated from reading ui file 'buzzer0904.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from functools import partial
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QLabel

from Basedir import basedir
from SerialController import serialController

class Buzzer_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(1150, 875)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")

        self.ComboBox = ComboBox(Form)
        self.ComboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.ComboBox.setObjectName("ComboBox")
        self.horizontalLayout_1.addWidget(self.ComboBox)
        # 添加示例曲目
        self.ComboBox.addItem("两只老虎")
        self.ComboBox.addItem("小星星")
        self.ComboBox.addItem("小幸运")
        self.ComboBox.addItem("致爱丽丝")
        self.ComboBox.addItem("菊花台")
        # 绑定ComboBox的信号
        self.ComboBox.currentIndexChanged.connect(self.on_combobox_changed)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem)
        self.DisplayLabel = DisplayLabel(Form)
        self.DisplayLabel.setObjectName("DisplayLabel")
        self.horizontalLayout_1.addWidget(self.DisplayLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_1)

        # 创建 QLabel 用于显示图片
        self.label = QLabel(Form)
        self.label.setFixedSize(1130, 500)  # 设置 QLabel 的大小
        self.label.setStyleSheet("border-radius: 8px;")  # 设置圆角边框样式
        self.label.setStyleSheet("""
            border: 1px solid rgba(0, 0, 0, 0.073);
            border-radius: 5px;
            border-bottom: 1px solid rgba(0, 0, 0, 0.183);
            padding: 2px 10px 3px 10px;
            background: rgba(255, 255, 255, 0.7);
            """)  # 设置边框样式和背景
        self.label.setAlignment(QtCore.Qt.AlignCenter)  # 设置图片居中对齐
        self.verticalLayout.addWidget(self.label)

        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")


        self.PushButton_1 = PushButton(Form)
        self.PushButton_1.setMinimumSize(QtCore.QSize(50, 250))
        self.PushButton_1.setObjectName("PushButton_1")
        self.horizontalLayout_2.addWidget(self.PushButton_1)
        self.PushButton_2 = PushButton(Form)
        self.PushButton_2.setMinimumSize(QtCore.QSize(50, 250))
        self.PushButton_2.setObjectName("PushButton_2")
        self.horizontalLayout_2.addWidget(self.PushButton_2)
        self.PushButton_3 = PushButton(Form)
        self.PushButton_3.setMinimumSize(QtCore.QSize(50, 250))
        self.PushButton_3.setObjectName("PushButton_3")
        self.horizontalLayout_2.addWidget(self.PushButton_3)
        self.PushButton_4 = PushButton(Form)
        self.PushButton_4.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_4.setObjectName("PushButton_4")
        self.horizontalLayout_2.addWidget(self.PushButton_4)
        self.PushButton_5 = PushButton(Form)
        self.PushButton_5.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_5.setObjectName("PushButton_5")
        self.horizontalLayout_2.addWidget(self.PushButton_5)
        self.PushButton_6 = PushButton(Form)
        self.PushButton_6.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_6.setObjectName("PushButton_6")
        self.horizontalLayout_2.addWidget(self.PushButton_6)
        self.PushButton_7 = PushButton(Form)
        self.PushButton_7.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_7.setObjectName("PushButton_7")
        self.horizontalLayout_2.addWidget(self.PushButton_7)
        self.PushButton_8 = PushButton(Form)
        self.PushButton_8.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_8.setObjectName("PushButton_8")
        self.horizontalLayout_2.addWidget(self.PushButton_8)
        self.PushButton_9 = PushButton(Form)
        self.PushButton_9.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_9.setObjectName("PushButton_9")
        self.horizontalLayout_2.addWidget(self.PushButton_9)
        self.PushButton_10 = PushButton(Form)
        self.PushButton_10.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_10.setObjectName("PushButton_10")
        self.horizontalLayout_2.addWidget(self.PushButton_10)
        self.PushButton_11 = PushButton(Form)
        self.PushButton_11.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_11.setObjectName("PushButton_11")
        self.horizontalLayout_2.addWidget(self.PushButton_11)
        self.PushButton_12 = PushButton(Form)
        self.PushButton_12.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_12.setObjectName("PushButton_12")
        self.horizontalLayout_2.addWidget(self.PushButton_12)
        self.PushButton_13 = PushButton(Form)
        self.PushButton_13.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_13.setObjectName("PushButton_13")
        self.horizontalLayout_2.addWidget(self.PushButton_13)
        self.PushButton_14 = PushButton(Form)
        self.PushButton_14.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_14.setObjectName("PushButton_14")
        self.horizontalLayout_2.addWidget(self.PushButton_14)
        self.PushButton_15 = PushButton(Form)
        self.PushButton_15.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_15.setObjectName("PushButton_15")
        self.horizontalLayout_2.addWidget(self.PushButton_15)
        self.PushButton_16 = PushButton(Form)
        self.PushButton_16.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_16.setObjectName("PushButton_16")
        self.horizontalLayout_2.addWidget(self.PushButton_16)
        self.PushButton_17 = PushButton(Form)
        self.PushButton_17.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_17.setObjectName("PushButton_17")
        self.horizontalLayout_2.addWidget(self.PushButton_17)
        self.PushButton_18 = PushButton(Form)
        self.PushButton_18.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_18.setObjectName("PushButton_18")
        self.horizontalLayout_2.addWidget(self.PushButton_18)
        self.PushButton_19 = PushButton(Form)
        self.PushButton_19.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_19.setObjectName("PushButton_19")
        self.horizontalLayout_2.addWidget(self.PushButton_19)
        self.PushButton_20 = PushButton(Form)
        self.PushButton_20.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_20.setObjectName("PushButton_20")
        self.horizontalLayout_2.addWidget(self.PushButton_20)
        self.PushButton_21 = PushButton(Form)
        self.PushButton_21.setMinimumSize(QtCore.QSize(50,  250))
        self.PushButton_21.setObjectName("PushButton_21")
        self.horizontalLayout_2.addWidget(self.PushButton_21)
        
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.PushButton_1.clicked.connect(partial(self.playthepiano, 1))
        self.PushButton_2.clicked.connect(partial(self.playthepiano, 2))
        self.PushButton_3.clicked.connect(partial(self.playthepiano, 3))
        self.PushButton_4.clicked.connect(partial(self.playthepiano, 4))
        self.PushButton_5.clicked.connect(partial(self.playthepiano, 5))
        self.PushButton_6.clicked.connect(partial(self.playthepiano, 6))
        self.PushButton_7.clicked.connect(partial(self.playthepiano, 7))
        self.PushButton_8.clicked.connect(partial(self.playthepiano, 8))
        self.PushButton_9.clicked.connect(partial(self.playthepiano, 9))
        self.PushButton_10.clicked.connect(partial(self.playthepiano, 10))
        self.PushButton_11.clicked.connect(partial(self.playthepiano, 11))
        self.PushButton_12.clicked.connect(partial(self.playthepiano, 12))
        self.PushButton_13.clicked.connect(partial(self.playthepiano, 13))
        self.PushButton_14.clicked.connect(partial(self.playthepiano, 14))
        self.PushButton_15.clicked.connect(partial(self.playthepiano, 15))
        self.PushButton_16.clicked.connect(partial(self.playthepiano, 16))
        self.PushButton_17.clicked.connect(partial(self.playthepiano, 17))
        self.PushButton_18.clicked.connect(partial(self.playthepiano, 18))
        self.PushButton_19.clicked.connect(partial(self.playthepiano, 19))
        self.PushButton_20.clicked.connect(partial(self.playthepiano, 20))
        self.PushButton_21.clicked.connect(partial(self.playthepiano, 21))

    def playthepiano(self,ID):
        # 当按钮被点击时，发送数据
        if   ID==1:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 1}))
        elif ID==2:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 2}))
        elif ID==3:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 3}))
        elif ID==4:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 4}))
        elif ID==5:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 5}))
        elif ID==6:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 6}))
        elif ID==7:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 7}))
        elif ID==8:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 8}))
        elif ID==9:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 9}))
        elif ID==10:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 10}))
        elif ID==11:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 11}))
        elif ID==12:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 12}))
        elif ID==13:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 13}))
        elif ID==14:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 14}))
        elif ID == 15:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 15}))
        elif ID == 16:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 16}))
        elif ID == 17:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 17}))
        elif ID == 18:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 18}))
        elif ID == 19:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 19}))
        elif ID == 20:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 20}))
        elif ID == 21:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 21}))
        else:
            serialController.send_data(json.dumps({"name": "Buzzer", "data": 0}))

    #显示曲谱图片
    def on_combobox_changed(self, index):
        # 当 ComboBox 选项改变时，更新 QLabel 的内容
        image_paths = {
            "两只老虎": os.path.join(basedir, 'resource', "两只老虎谱.png"),
            "小星星": os.path.join(basedir, 'resource', "小星星谱.png"),
             "小幸运": os.path.join(basedir, 'resource', "小幸运谱.png"),
             "致爱丽丝": os.path.join(basedir, 'resource', "致爱丽丝谱.png"),
             "菊花台": os.path.join(basedir, 'resource', "菊花台谱.png")
        }
        selected_item = self.ComboBox.currentText()
        pixmap = QPixmap(image_paths[selected_item])
        self.label.setPixmap(pixmap)
        self.label.move(250, 100)# 设置QLabel的位置

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ComboBox.setText(_translate("Form", "示例曲谱"))
        self.DisplayLabel.setText(_translate("Form", "电子琴模拟器"))
        self.PushButton_1.setText(_translate("Form", "低1"))
        self.PushButton_2.setText(_translate("Form", "低2"))
        self.PushButton_3.setText(_translate("Form", "低3"))
        self.PushButton_4.setText(_translate("Form", "低4"))
        self.PushButton_5.setText(_translate("Form", "低5"))
        self.PushButton_6.setText(_translate("Form", "低6"))
        self.PushButton_7.setText(_translate("Form", "低7"))
        self.PushButton_8.setText(_translate("Form", "中1"))
        self.PushButton_9.setText(_translate("Form", "中2"))
        self.PushButton_10.setText(_translate("Form", "中3"))
        self.PushButton_11.setText(_translate("Form", "中4"))
        self.PushButton_12.setText(_translate("Form", "中5"))
        self.PushButton_13.setText(_translate("Form", "中6"))
        self.PushButton_14.setText(_translate("Form", "中7"))
        self.PushButton_15.setText(_translate("Form", "高1"))
        self.PushButton_16.setText(_translate("Form", "高2"))
        self.PushButton_17.setText(_translate("Form", "高3"))
        self.PushButton_18.setText(_translate("Form", "高4"))
        self.PushButton_19.setText(_translate("Form", "高5"))
        self.PushButton_20.setText(_translate("Form", "高6"))
        self.PushButton_21.setText(_translate("Form", "高7"))
from qfluentwidgets import ComboBox, DisplayLabel, PushButton, ImageLabel

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Buzzer_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())