# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'empty.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QUrl
from qframelesswindow.webengine import FramelessWebEngineView


class Ui_Main(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1111, 782)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SingleDirectionScrollArea = SingleDirectionScrollArea(Frame)
        self.SingleDirectionScrollArea.setWidgetResizable(True)
        self.SingleDirectionScrollArea.setObjectName("SingleDirectionScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 960, 762))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PushButton = PushButton(self.scrollAreaWidgetContents)
        self.PushButton.setObjectName("PushButton")
        self.webView = FramelessWebEngineView(Frame)
        self.Path = QUrl("index.html")
        self.Path.setUrl("file:///C:/Users/Admin/PycharmProjects/PYQT5_Project/resource/index.html")
        self.webView.load(self.Path)
        self.verticalLayout.addWidget(self.PushButton)
        self.verticalLayout.addWidget(self.webView)
        self.SingleDirectionScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.SingleDirectionScrollArea)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TitleLabel = TitleLabel(Frame)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout_2.addWidget(self.TitleLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.PushButton.setText(_translate("Frame", "Push button"))
        self.TitleLabel.setText(_translate("Frame", "Title label"))
from qfluentwidgets import PushButton, SingleDirectionScrollArea, TitleLabel
