# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fram.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PythonHighlighter import PythonHighlighter


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(854, 859)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleLabel = TitleLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleLabel.sizePolicy().hasHeightForWidth())
        self.TitleLabel.setSizePolicy(sizePolicy)
        self.TitleLabel.setMaximumSize(QtCore.QSize(500, 100))
        self.TitleLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        self.TextEdit = TextEdit(Frame)
        self.TextEdit.setObjectName("TextEdit")
        self.verticalLayout.addWidget(self.TextEdit)
        self.PushButton = PushButton(Frame)
        self.PushButton.setObjectName("PushButton")
        self.verticalLayout.addWidget(self.PushButton)

        self.retranslateUi(Frame)

        # self.highlighter = PythonHighlighter(self.TextEdit.document())
        self.highlighter = PythonHighlighter(self.TextEdit.document())

        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.TitleLabel.setText(_translate("Frame", "Python代码编辑区"))
        self.PushButton.setText(_translate("Frame", "应用"))
from qfluentwidgets import PushButton, TextEdit, TitleLabel
