# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'markdown.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from Basedir import basedir


class Ui_Markdown_Form(object):
    def setupUi(self, Markdown_Form):
        Markdown_Form.setObjectName("Markdown_Form")
        Markdown_Form.resize(480, 640)
        self.setWindowIcon(QIcon(os.path.join(basedir, 'resource', "logo.png")))
        self.verticalLayout = QtWidgets.QVBoxLayout(Markdown_Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleLabel = TitleLabel(Markdown_Form)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 550, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.BodyLabel = BodyLabel(Markdown_Form)
        self.BodyLabel.setTextFormat(QtCore.Qt.MarkdownText)
        self.BodyLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.BodyLabel.setWordWrap(True)
        self.BodyLabel.setObjectName("BodyLabel")
        self.BodyLabel.setText(self.loadMarkdown(os.path.join(basedir, 'resource', "超声波模块.md")))
        self.verticalLayout.addWidget(self.BodyLabel)

        self.retranslateUi(Markdown_Form)
        QtCore.QMetaObject.connectSlotsByName(Markdown_Form)

    def loadMarkdown(self, file_path):
        try:
            with open(file_path, 'r', encoding='utf-8') as file:
                markdown_text = file.read()
                return markdown_text
        except UnicodeDecodeError as e:
            print(f"Error reading file {file_path}: {e}")

    def retranslateUi(self, Markdown_Form):
        _translate = QtCore.QCoreApplication.translate
        Markdown_Form.setWindowTitle(_translate("Markdown_Form", "Form"))
        self.TitleLabel.setText(_translate("Markdown_Form", "超声波测距离实验"))
from qfluentwidgets import BodyLabel, TitleLabel
