# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newdow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(482, 545)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.AvatarWidget = AvatarWidget(Form)
        self.AvatarWidget.setObjectName("AvatarWidget")
        self.verticalLayout_2.addWidget(self.AvatarWidget, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TitleLabel = TitleLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setProperty("pixelFontSize", 17)
        self.TitleLabel.setObjectName("TitleLabel")
        self.horizontalLayout.addWidget(self.TitleLabel)
        self.LineEdit = LineEdit(Form)
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout.addWidget(self.LineEdit)
        self.PushButton = PushButton(Form)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout.addWidget(self.PushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TitleLabel_2 = TitleLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.TitleLabel_2.setFont(font)
        self.TitleLabel_2.setProperty("pixelFontSize", 17)
        self.TitleLabel_2.setObjectName("TitleLabel_2")
        self.horizontalLayout_2.addWidget(self.TitleLabel_2)
        self.ComboBox = ComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox.sizePolicy().hasHeightForWidth())
        self.ComboBox.setSizePolicy(sizePolicy)
        self.ComboBox.setObjectName("ComboBox")
        self.horizontalLayout_2.addWidget(self.ComboBox)
        self.PushButton_2 = PushButton(Form)
        self.PushButton_2.setObjectName("PushButton_2")
        self.horizontalLayout_2.addWidget(self.PushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.BodyLabel = BodyLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.BodyLabel.setFont(font)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout_2.addWidget(self.BodyLabel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TitleLabel.setText(_translate("Form", "路径:"))
        self.PushButton.setText(_translate("Form", "选择文件"))
        self.TitleLabel_2.setText(_translate("Form", "端口:"))
        self.PushButton_2.setText(_translate("Form", "下载程序"))
        self.BodyLabel.setText(_translate("Form", "Body label"))
from qfluentwidgets import AvatarWidget, BodyLabel, ComboBox, LineEdit, PushButton, TitleLabel
