# -*- coding: utf-8 -*-
import os

from PyQt5.QtGui import QIcon, QPixmap, QBrush, QPalette
from qfluentwidgets import BodyLabel, CaptionLabel, ComboBox, LineEdit, PushButton, SwitchButton, TitleLabel
from PyQt5 import QtCore, QtGui, QtWidgets

from Basedir import basedir


class Ui_Screen_Form(object):
    def setupUi(self, Screen_Form):
        Screen_Form.setObjectName("Screen_Form")
        Screen_Form.setFixedSize(640, 480)
        Screen_Form.setWindowIcon(QIcon(os.path.join(basedir, 'resource', "logo.png")))
        # 设置背景图片
        # palette = Screen_Form.palette()
        # palette.setBrush(QPalette.Window, QBrush(QPixmap(os.path.join(basedir, 'resource', "screen_bg.png"))))
        # Screen_Form.setPalette(palette)

        self.horizontalLayoutWidget = QtWidgets.QWidget(Screen_Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(95, 320, 481, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bodyLineEdit = LineEdit(self.horizontalLayoutWidget)
        self.bodyLineEdit.setObjectName("bodyLineEdit")
        self.horizontalLayout.addWidget(self.bodyLineEdit)
        self.PushButton = PushButton(self.horizontalLayoutWidget)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout.addWidget(self.PushButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Screen_Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(95, 370, 411, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CaptionLabel = CaptionLabel(self.horizontalLayoutWidget_2)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.horizontalLayout_2.addWidget(self.CaptionLabel)
        self.coverButton = SwitchButton(self.horizontalLayoutWidget_2)
        self.coverButton.setObjectName("coverButton")
        self.coverButton.setChecked(True)
        self.horizontalLayout_2.addWidget(self.coverButton)
        self.horizontalLayout_2.setStretch(0, 1)
        self.sizeBox = ComboBox(Screen_Form)
        self.sizeBox.setGeometry(QtCore.QRect(391, 290, 114, 32))
        self.sizeBox.setObjectName("sizeBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Screen_Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(95, 240, 151, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CaptionLabel_2 = CaptionLabel(self.verticalLayoutWidget)
        self.CaptionLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.CaptionLabel_2.setProperty("pixelFontSize", 18)
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.verticalLayout.addWidget(self.CaptionLabel_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CaptionLabel_3 = CaptionLabel(self.verticalLayoutWidget)
        self.CaptionLabel_3.setProperty("pixelFontSize", 16)
        self.CaptionLabel_3.setObjectName("CaptionLabel_3")
        self.horizontalLayout_3.addWidget(self.CaptionLabel_3)
        self.edit_x = LineEdit(self.verticalLayoutWidget)
        self.edit_x.setObjectName("edit_x")
        self.horizontalLayout_3.addWidget(self.edit_x)
        self.CaptionLabel_4 = CaptionLabel(self.verticalLayoutWidget)
        self.CaptionLabel_4.setProperty("pixelFontSize", 16)
        self.CaptionLabel_4.setObjectName("CaptionLabel_4")
        self.horizontalLayout_3.addWidget(self.CaptionLabel_4)
        self.edit_y = LineEdit(self.verticalLayoutWidget)
        self.edit_y.setObjectName("edit_y")
        self.horizontalLayout_3.addWidget(self.edit_y)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Screen_Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(95, 410, 411, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CaptionLabel_5 = CaptionLabel(self.horizontalLayoutWidget_4)
        self.CaptionLabel_5.setObjectName("CaptionLabel_5")
        self.horizontalLayout_4.addWidget(self.CaptionLabel_5)
        self.scrollButton = SwitchButton(self.horizontalLayoutWidget_4)
        self.scrollButton.setObjectName("scrollButton")
        self.horizontalLayout_4.addWidget(self.scrollButton)
        self.horizontalLayout_4.setStretch(0, 1)
        self.TitleLabel = TitleLabel(Screen_Form)
        self.TitleLabel.setGeometry(QtCore.QRect(250, 10, 161, 51))
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.BodyLabel = BodyLabel(Screen_Form)
        self.BodyLabel.setGeometry(QtCore.QRect(20, 110, 601, 71))
        self.BodyLabel.setWordWrap(True)
        self.BodyLabel.setObjectName("BodyLabel")

        self.retranslateUi(Screen_Form)
        QtCore.QMetaObject.connectSlotsByName(Screen_Form)

    def retranslateUi(self, Screen_Form):
        _translate = QtCore.QCoreApplication.translate
        Screen_Form.setWindowTitle(_translate("Screen_Form", "显示屏实验"))
        self.PushButton.setText(_translate("Screen_Form", "设置"))
        self.CaptionLabel.setText(_translate("Screen_Form", "覆盖显示"))
        self.CaptionLabel_2.setText(_translate("Screen_Form", "起始位置"))
        self.CaptionLabel_3.setText(_translate("Screen_Form", "x:"))
        self.CaptionLabel_4.setText(_translate("Screen_Form", "y:"))
        self.CaptionLabel_5.setText(_translate("Screen_Form", "文字滚动"))
        self.TitleLabel.setText(_translate("Screen_Form", "显示屏实验"))
        self.BodyLabel.setText(_translate("Screen_Form", "        OLED显示屏由自发光材料组成，在生活中应用广泛，如电子灯牌，广告牌，等大多是由OLED显示屏构成显示，我们使用实验箱屏幕可以模拟广告牌效果，实现自定义文本位置，覆盖显示，文字滚动等效果。"))

