# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Test_Form(object):
    def setupUi(self, Test_Form):
        Test_Form.setObjectName("Test_Form")
        Test_Form.resize(484, 437)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Test_Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 160, 381, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CaptionLabel = CaptionLabel(self.horizontalLayoutWidget)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.horizontalLayout.addWidget(self.CaptionLabel)
        self.CaptionLabel_2 = CaptionLabel(self.horizontalLayoutWidget)
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.horizontalLayout.addWidget(self.CaptionLabel_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.PushButton = PushButton(self.horizontalLayoutWidget)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout.addWidget(self.PushButton)

        self.retranslateUi(Test_Form)
        QtCore.QMetaObject.connectSlotsByName(Test_Form)

    def retranslateUi(self, Test_Form):
        _translate = QtCore.QCoreApplication.translate
        Test_Form.setWindowTitle(_translate("Test_Form", "Form"))
        self.CaptionLabel.setText(_translate("Test_Form", "分数:"))
        self.CaptionLabel_2.setText(_translate("Test_Form", "10"))
        self.PushButton.setText(_translate("Test_Form", "Push button"))
from qfluentwidgets import CaptionLabel, PushButton
