# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'ultrasonic.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

from Basedir import basedir


class Ui_Us_Form(object):
    def setupUi(self, Us_Form):
        Us_Form.setObjectName("Us_Form")
        Us_Form.setFixedSize(950, 640)
        Us_Form.setMouseTracking(True)
        self.setWindowIcon(QIcon(os.path.join(basedir, 'resource', "logo.png")))
        self.verticalLayout = QtWidgets.QVBoxLayout(Us_Form)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ultrasonic_Title = TitleLabel(Us_Form)
        self.ultrasonic_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.ultrasonic_Title.setObjectName("ultrasonic_Title")
        self.verticalLayout.addWidget(self.ultrasonic_Title)
        self.BodyLabel = BodyLabel(Us_Form)
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Us_Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Us_Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.BodyLabel_2 = BodyLabel(Us_Form)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.verticalLayout.addWidget(self.BodyLabel_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PrimaryPushButton = PrimaryPushButton(Us_Form)
        self.PrimaryPushButton.setEnabled(True)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.horizontalLayout.addWidget(self.PrimaryPushButton)
        self.ultrasonic_value = LineEdit(Us_Form)
        self.ultrasonic_value.setEnabled(True)
        self.ultrasonic_value.setMouseTracking(False)
        self.ultrasonic_value.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ultrasonic_value.setText("")
        self.ultrasonic_value.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ultrasonic_value.setObjectName("ultrasonic_value")
        self.horizontalLayout.addWidget(self.ultrasonic_value)
        self.PushButton = PushButton(Us_Form)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout.addWidget(self.PushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Us_Form)
        QtCore.QMetaObject.connectSlotsByName(Us_Form)

    def retranslateUi(self, Us_Form):
        _translate = QtCore.QCoreApplication.translate
        Us_Form.setWindowTitle(_translate("Us_Form", "超声波测距实验"))
        self.ultrasonic_Title.setText(_translate("Us_Form", "超声波测距实验"))
        self.BodyLabel.setText(_translate("Us_Form", "这是一段超声波传感器的原理介绍"))
        self.label.setText(_translate("Us_Form", "TextLabel"))
        self.label_2.setText(_translate("Us_Form", "TextLabel"))
        self.BodyLabel_2.setText(_translate("Us_Form", "再来一段介绍"))
        self.PrimaryPushButton.setText(_translate("Us_Form", "距离"))
        self.PushButton.setText(_translate("Us_Form", "CM"))
from qfluentwidgets import BodyLabel, LineEdit, PrimaryPushButton, PushButton, TitleLabel
